spring:
  application:
    name: hr
  profiles:
    active: smart
hr:
  employees:
    salary:
      limit:
        first-category: 10.0
        second-category: 5.0
        third-category: 2.5
      percentage:
        first-category: 30
        second-category: 15
        third-category: 6
        fourth-category: 0
