spring:
  application:
    name: hr
  profiles:
    active: smart
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
hr:
  employees:
    salary:
      limit:
        first-category: 10.0
        second-category: 5.0
        third-category: 2.5
      percentage:
        first-category: 30
        second-category: 15
        third-category: 6
        fourth-category: 0
